### ISSUE TITLE
can add a win10 support?

### ISSUE THREAD

**Issue by mipoem** [Code52/DownmarkerWPF#450]
I was use Win10 system,but it not work correctly.

**Comment by shiftkey** [comment]
Can you tell me if there are any errors or Event Viewer entries that might explain why it's not working?

**Comment by mipoem** [comment]
yes, it will crash down when it finished install, and windows will automatic collection the message,it will not present any errors and something else. Then i click the icon in the start menu,it will not give any responses, just nothing. So if there is any log files in the installation folder that i can upload to you for fix the problem?

**Comment by shiftkey** [comment]
Check Event Viewer, there should be some gold in there...

**Comment by mipoem** [comment]
>Check Event Viewer, there should be some gold in there...

ok, I get all logs and files I can find in Event Viewer, and i have upload to github [MarkPadError in Win10](https://github.com/mipoem/MPError)

**Comment by shiftkey** [comment]
```
Application: GitHub.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.TypeInitializationException
Stack:
   at System.Lazy`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].CreateValue()
   at System.Lazy`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].LazyInitValue()
   at System.Lazy`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].get_Value()
   at GitHub.Helpers.SharedCache.get_UserAccount()
   at GitHub.Models.UserSettingsModel.Refresh()
   at GitHub.Helpers.StartupManager.PrepareUserSettings()
   at GitHub.AppStartup.StartupSequence.Start(GitHub.Helpers.IStartupManager)
   at GitHub.Helpers.AppBootstrapper.StartApp()
   at GitHub.App..ctor()
   at GitHub.App.Main()
```

and

```
Application: MarkPad.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.IO.FileNotFoundException
Stack:
   at MarkPad.Preview.HtmlPreview.Init()
   at MarkPad.App..ctor()
   at MarkPad.App.Main()
```

**Comment by mipoem** [comment]
> Application: GitHub.exe

Sorry, I search "mark" in the Viewer to get this.

Is there any message useful?

**Comment by shiftkey** [comment]
@mipoem apologies, I just scanned for errors. I'll drop that one.

**Comment by mipoem** [comment]
I get something new, a hide folder named [LocalMetaData](https://github.com/mipoem/MPError/tree/master/LocaleMetaData) which generate by OS. I am a new coder,so i didn't know if this is something helpful.

**Comment by ghost** [comment]
I had exactly he same issue until I installed Visual Studio 2015 (Community Edition). Not sure which library fixed the issue though.
